
package com.bluetop.engin.api.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-03-31T21:44:18.450+08:00
 * Generated source version: 3.4.3
 *
 */
public final class WorkflowServicePortType_WorkflowServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("webservices.services.weaver.com.cn", "WorkflowService");

    private WorkflowServicePortType_WorkflowServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WorkflowService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WorkflowService ss = new WorkflowService(wsdlURL, SERVICE_NAME);
        WorkflowServicePortType port = ss.getWorkflowServiceHttpPort();

        {
        System.out.println("Invoking getHendledWorkflowRequestCount4Ofs...");
        int _getHendledWorkflowRequestCount4Ofs_in0 = 0;
        ArrayOfString _getHendledWorkflowRequestCount4Ofs_in1 = null;
        boolean _getHendledWorkflowRequestCount4Ofs_in2 = false;
        int _getHendledWorkflowRequestCount4Ofs__return = port.getHendledWorkflowRequestCount4Ofs(_getHendledWorkflowRequestCount4Ofs_in0, _getHendledWorkflowRequestCount4Ofs_in1, _getHendledWorkflowRequestCount4Ofs_in2);
        System.out.println("getHendledWorkflowRequestCount4Ofs.result=" + _getHendledWorkflowRequestCount4Ofs__return);


        }
        {
        System.out.println("Invoking getMyWorkflowRequestList4OS...");
        int _getMyWorkflowRequestList4OS_in0 = 0;
        int _getMyWorkflowRequestList4OS_in1 = 0;
        int _getMyWorkflowRequestList4OS_in2 = 0;
        int _getMyWorkflowRequestList4OS_in3 = 0;
        ArrayOfString _getMyWorkflowRequestList4OS_in4 = null;
        boolean _getMyWorkflowRequestList4OS_in5 = false;
        ArrayOfWorkflowRequestInfo _getMyWorkflowRequestList4OS__return = port.getMyWorkflowRequestList4OS(_getMyWorkflowRequestList4OS_in0, _getMyWorkflowRequestList4OS_in1, _getMyWorkflowRequestList4OS_in2, _getMyWorkflowRequestList4OS_in3, _getMyWorkflowRequestList4OS_in4, _getMyWorkflowRequestList4OS_in5);
        System.out.println("getMyWorkflowRequestList4OS.result=" + _getMyWorkflowRequestList4OS__return);


        }
        {
        System.out.println("Invoking getCreateWorkflowTypeList...");
        int _getCreateWorkflowTypeList_in0 = 0;
        int _getCreateWorkflowTypeList_in1 = 0;
        int _getCreateWorkflowTypeList_in2 = 0;
        int _getCreateWorkflowTypeList_in3 = 0;
        ArrayOfString _getCreateWorkflowTypeList_in4 = null;
        ArrayOfWorkflowBaseInfo _getCreateWorkflowTypeList__return = port.getCreateWorkflowTypeList(_getCreateWorkflowTypeList_in0, _getCreateWorkflowTypeList_in1, _getCreateWorkflowTypeList_in2, _getCreateWorkflowTypeList_in3, _getCreateWorkflowTypeList_in4);
        System.out.println("getCreateWorkflowTypeList.result=" + _getCreateWorkflowTypeList__return);


        }
        {
        System.out.println("Invoking getBeRejectWorkflowRequestCount...");
        int _getBeRejectWorkflowRequestCount_in0 = 0;
        ArrayOfString _getBeRejectWorkflowRequestCount_in1 = null;
        int _getBeRejectWorkflowRequestCount__return = port.getBeRejectWorkflowRequestCount(_getBeRejectWorkflowRequestCount_in0, _getBeRejectWorkflowRequestCount_in1);
        System.out.println("getBeRejectWorkflowRequestCount.result=" + _getBeRejectWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getProcessedWorkflowRequestCount4OS...");
        int _getProcessedWorkflowRequestCount4OS_in0 = 0;
        ArrayOfString _getProcessedWorkflowRequestCount4OS_in1 = null;
        boolean _getProcessedWorkflowRequestCount4OS_in2 = false;
        int _getProcessedWorkflowRequestCount4OS__return = port.getProcessedWorkflowRequestCount4OS(_getProcessedWorkflowRequestCount4OS_in0, _getProcessedWorkflowRequestCount4OS_in1, _getProcessedWorkflowRequestCount4OS_in2);
        System.out.println("getProcessedWorkflowRequestCount4OS.result=" + _getProcessedWorkflowRequestCount4OS__return);


        }
        {
        System.out.println("Invoking getCCWorkflowRequestList...");
        int _getCCWorkflowRequestList_in0 = 0;
        int _getCCWorkflowRequestList_in1 = 0;
        int _getCCWorkflowRequestList_in2 = 0;
        int _getCCWorkflowRequestList_in3 = 0;
        ArrayOfString _getCCWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getCCWorkflowRequestList__return = port.getCCWorkflowRequestList(_getCCWorkflowRequestList_in0, _getCCWorkflowRequestList_in1, _getCCWorkflowRequestList_in2, _getCCWorkflowRequestList_in3, _getCCWorkflowRequestList_in4);
        System.out.println("getCCWorkflowRequestList.result=" + _getCCWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking givingOpinions...");
        int _givingOpinions_in0 = 0;
        int _givingOpinions_in1 = 0;
        String _givingOpinions_in2 = "";
        String _givingOpinions__return = port.givingOpinions(_givingOpinions_in0, _givingOpinions_in1, _givingOpinions_in2);
        System.out.println("givingOpinions.result=" + _givingOpinions__return);


        }
        {
        System.out.println("Invoking getToDoWorkflowRequestCount...");
        int _getToDoWorkflowRequestCount_in0 = 0;
        ArrayOfString _getToDoWorkflowRequestCount_in1 = null;
        int _getToDoWorkflowRequestCount__return = port.getToDoWorkflowRequestCount(_getToDoWorkflowRequestCount_in0, _getToDoWorkflowRequestCount_in1);
        System.out.println("getToDoWorkflowRequestCount.result=" + _getToDoWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getForwardWorkflowRequestCount...");
        int _getForwardWorkflowRequestCount_in0 = 0;
        ArrayOfString _getForwardWorkflowRequestCount_in1 = null;
        int _getForwardWorkflowRequestCount__return = port.getForwardWorkflowRequestCount(_getForwardWorkflowRequestCount_in0, _getForwardWorkflowRequestCount_in1);
        System.out.println("getForwardWorkflowRequestCount.result=" + _getForwardWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getProcessedWorkflowRequestList4OS...");
        int _getProcessedWorkflowRequestList4OS_in0 = 0;
        int _getProcessedWorkflowRequestList4OS_in1 = 0;
        int _getProcessedWorkflowRequestList4OS_in2 = 0;
        int _getProcessedWorkflowRequestList4OS_in3 = 0;
        ArrayOfString _getProcessedWorkflowRequestList4OS_in4 = null;
        boolean _getProcessedWorkflowRequestList4OS_in5 = false;
        ArrayOfWorkflowRequestInfo _getProcessedWorkflowRequestList4OS__return = port.getProcessedWorkflowRequestList4OS(_getProcessedWorkflowRequestList4OS_in0, _getProcessedWorkflowRequestList4OS_in1, _getProcessedWorkflowRequestList4OS_in2, _getProcessedWorkflowRequestList4OS_in3, _getProcessedWorkflowRequestList4OS_in4, _getProcessedWorkflowRequestList4OS_in5);
        System.out.println("getProcessedWorkflowRequestList4OS.result=" + _getProcessedWorkflowRequestList4OS__return);


        }
        {
        System.out.println("Invoking getProcessedWorkflowRequestList...");
        int _getProcessedWorkflowRequestList_in0 = 0;
        int _getProcessedWorkflowRequestList_in1 = 0;
        int _getProcessedWorkflowRequestList_in2 = 0;
        int _getProcessedWorkflowRequestList_in3 = 0;
        ArrayOfString _getProcessedWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getProcessedWorkflowRequestList__return = port.getProcessedWorkflowRequestList(_getProcessedWorkflowRequestList_in0, _getProcessedWorkflowRequestList_in1, _getProcessedWorkflowRequestList_in2, _getProcessedWorkflowRequestList_in3, _getProcessedWorkflowRequestList_in4);
        System.out.println("getProcessedWorkflowRequestList.result=" + _getProcessedWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking doForceOver...");
        int _doForceOver_in0 = 0;
        int _doForceOver_in1 = 0;
        String _doForceOver__return = port.doForceOver(_doForceOver_in0, _doForceOver_in1);
        System.out.println("doForceOver.result=" + _doForceOver__return);


        }
        {
        System.out.println("Invoking getToDoWorkflowRequestCount4OS...");
        int _getToDoWorkflowRequestCount4OS_in0 = 0;
        ArrayOfString _getToDoWorkflowRequestCount4OS_in1 = null;
        boolean _getToDoWorkflowRequestCount4OS_in2 = false;
        int _getToDoWorkflowRequestCount4OS__return = port.getToDoWorkflowRequestCount4OS(_getToDoWorkflowRequestCount4OS_in0, _getToDoWorkflowRequestCount4OS_in1, _getToDoWorkflowRequestCount4OS_in2);
        System.out.println("getToDoWorkflowRequestCount4OS.result=" + _getToDoWorkflowRequestCount4OS__return);


        }
        {
        System.out.println("Invoking doCreateWorkflowRequest...");
        WorkflowRequestInfo _doCreateWorkflowRequest_in0 = null;
        int _doCreateWorkflowRequest_in1 = 0;
        String _doCreateWorkflowRequest__return = port.doCreateWorkflowRequest(_doCreateWorkflowRequest_in0, _doCreateWorkflowRequest_in1);
        System.out.println("doCreateWorkflowRequest.result=" + _doCreateWorkflowRequest__return);


        }
        {
        System.out.println("Invoking getCreateWorkflowRequestInfo...");
        int _getCreateWorkflowRequestInfo_in0 = 0;
        int _getCreateWorkflowRequestInfo_in1 = 0;
        WorkflowRequestInfo _getCreateWorkflowRequestInfo__return = port.getCreateWorkflowRequestInfo(_getCreateWorkflowRequestInfo_in0, _getCreateWorkflowRequestInfo_in1);
        System.out.println("getCreateWorkflowRequestInfo.result=" + _getCreateWorkflowRequestInfo__return);


        }
        {
        System.out.println("Invoking getHendledWorkflowRequestList4Ofs...");
        int _getHendledWorkflowRequestList4Ofs_in0 = 0;
        int _getHendledWorkflowRequestList4Ofs_in1 = 0;
        int _getHendledWorkflowRequestList4Ofs_in2 = 0;
        int _getHendledWorkflowRequestList4Ofs_in3 = 0;
        ArrayOfString _getHendledWorkflowRequestList4Ofs_in4 = null;
        boolean _getHendledWorkflowRequestList4Ofs_in5 = false;
        ArrayOfWorkflowRequestInfo _getHendledWorkflowRequestList4Ofs__return = port.getHendledWorkflowRequestList4Ofs(_getHendledWorkflowRequestList4Ofs_in0, _getHendledWorkflowRequestList4Ofs_in1, _getHendledWorkflowRequestList4Ofs_in2, _getHendledWorkflowRequestList4Ofs_in3, _getHendledWorkflowRequestList4Ofs_in4, _getHendledWorkflowRequestList4Ofs_in5);
        System.out.println("getHendledWorkflowRequestList4Ofs.result=" + _getHendledWorkflowRequestList4Ofs__return);


        }
        {
        System.out.println("Invoking getCCWorkflowRequestList4OS...");
        int _getCCWorkflowRequestList4OS_in0 = 0;
        int _getCCWorkflowRequestList4OS_in1 = 0;
        int _getCCWorkflowRequestList4OS_in2 = 0;
        int _getCCWorkflowRequestList4OS_in3 = 0;
        ArrayOfString _getCCWorkflowRequestList4OS_in4 = null;
        boolean _getCCWorkflowRequestList4OS_in5 = false;
        ArrayOfWorkflowRequestInfo _getCCWorkflowRequestList4OS__return = port.getCCWorkflowRequestList4OS(_getCCWorkflowRequestList4OS_in0, _getCCWorkflowRequestList4OS_in1, _getCCWorkflowRequestList4OS_in2, _getCCWorkflowRequestList4OS_in3, _getCCWorkflowRequestList4OS_in4, _getCCWorkflowRequestList4OS_in5);
        System.out.println("getCCWorkflowRequestList4OS.result=" + _getCCWorkflowRequestList4OS__return);


        }
        {
        System.out.println("Invoking getLeaveDays...");
        String _getLeaveDays_in0 = "";
        String _getLeaveDays_in1 = "";
        String _getLeaveDays_in2 = "";
        String _getLeaveDays_in3 = "";
        String _getLeaveDays_in4 = "";
        String _getLeaveDays__return = port.getLeaveDays(_getLeaveDays_in0, _getLeaveDays_in1, _getLeaveDays_in2, _getLeaveDays_in3, _getLeaveDays_in4);
        System.out.println("getLeaveDays.result=" + _getLeaveDays__return);


        }
        {
        System.out.println("Invoking getMyWorkflowRequestCount4OS...");
        int _getMyWorkflowRequestCount4OS_in0 = 0;
        ArrayOfString _getMyWorkflowRequestCount4OS_in1 = null;
        boolean _getMyWorkflowRequestCount4OS_in2 = false;
        int _getMyWorkflowRequestCount4OS__return = port.getMyWorkflowRequestCount4OS(_getMyWorkflowRequestCount4OS_in0, _getMyWorkflowRequestCount4OS_in1, _getMyWorkflowRequestCount4OS_in2);
        System.out.println("getMyWorkflowRequestCount4OS.result=" + _getMyWorkflowRequestCount4OS__return);


        }
        {
        System.out.println("Invoking doCreateRequest...");
        WorkflowRequestInfo _doCreateRequest_in0 = null;
        int _doCreateRequest_in1 = 0;
        String _doCreateRequest__return = port.doCreateRequest(_doCreateRequest_in0, _doCreateRequest_in1);
        System.out.println("doCreateRequest.result=" + _doCreateRequest__return);


        }
        {
        System.out.println("Invoking getProcessedWorkflowRequestCount...");
        int _getProcessedWorkflowRequestCount_in0 = 0;
        ArrayOfString _getProcessedWorkflowRequestCount_in1 = null;
        int _getProcessedWorkflowRequestCount__return = port.getProcessedWorkflowRequestCount(_getProcessedWorkflowRequestCount_in0, _getProcessedWorkflowRequestCount_in1);
        System.out.println("getProcessedWorkflowRequestCount.result=" + _getProcessedWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getCreateWorkflowList...");
        int _getCreateWorkflowList_in0 = 0;
        int _getCreateWorkflowList_in1 = 0;
        int _getCreateWorkflowList_in2 = 0;
        int _getCreateWorkflowList_in3 = 0;
        int _getCreateWorkflowList_in4 = 0;
        ArrayOfString _getCreateWorkflowList_in5 = null;
        ArrayOfWorkflowBaseInfo _getCreateWorkflowList__return = port.getCreateWorkflowList(_getCreateWorkflowList_in0, _getCreateWorkflowList_in1, _getCreateWorkflowList_in2, _getCreateWorkflowList_in3, _getCreateWorkflowList_in4, _getCreateWorkflowList_in5);
        System.out.println("getCreateWorkflowList.result=" + _getCreateWorkflowList__return);


        }
        {
        System.out.println("Invoking getWorkflowRequest...");
        int _getWorkflowRequest_in0 = 0;
        int _getWorkflowRequest_in1 = 0;
        int _getWorkflowRequest_in2 = 0;
        WorkflowRequestInfo _getWorkflowRequest__return = port.getWorkflowRequest(_getWorkflowRequest_in0, _getWorkflowRequest_in1, _getWorkflowRequest_in2);
        System.out.println("getWorkflowRequest.result=" + _getWorkflowRequest__return);


        }
        {
        System.out.println("Invoking getWorkflowRequest4Split...");
        int _getWorkflowRequest4Split_in0 = 0;
        int _getWorkflowRequest4Split_in1 = 0;
        int _getWorkflowRequest4Split_in2 = 0;
        int _getWorkflowRequest4Split_in3 = 0;
        WorkflowRequestInfo _getWorkflowRequest4Split__return = port.getWorkflowRequest4Split(_getWorkflowRequest4Split_in0, _getWorkflowRequest4Split_in1, _getWorkflowRequest4Split_in2, _getWorkflowRequest4Split_in3);
        System.out.println("getWorkflowRequest4Split.result=" + _getWorkflowRequest4Split__return);


        }
        {
        System.out.println("Invoking submitWorkflowRequest...");
        WorkflowRequestInfo _submitWorkflowRequest_in0 = null;
        int _submitWorkflowRequest_in1 = 0;
        int _submitWorkflowRequest_in2 = 0;
        String _submitWorkflowRequest_in3 = "";
        String _submitWorkflowRequest_in4 = "";
        String _submitWorkflowRequest__return = port.submitWorkflowRequest(_submitWorkflowRequest_in0, _submitWorkflowRequest_in1, _submitWorkflowRequest_in2, _submitWorkflowRequest_in3, _submitWorkflowRequest_in4);
        System.out.println("submitWorkflowRequest.result=" + _submitWorkflowRequest__return);


        }
        {
        System.out.println("Invoking getHendledWorkflowRequestList...");
        int _getHendledWorkflowRequestList_in0 = 0;
        int _getHendledWorkflowRequestList_in1 = 0;
        int _getHendledWorkflowRequestList_in2 = 0;
        int _getHendledWorkflowRequestList_in3 = 0;
        ArrayOfString _getHendledWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getHendledWorkflowRequestList__return = port.getHendledWorkflowRequestList(_getHendledWorkflowRequestList_in0, _getHendledWorkflowRequestList_in1, _getHendledWorkflowRequestList_in2, _getHendledWorkflowRequestList_in3, _getHendledWorkflowRequestList_in4);
        System.out.println("getHendledWorkflowRequestList.result=" + _getHendledWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking getWorkflowNewFlag...");
        ArrayOfString _getWorkflowNewFlag_in0 = null;
        String _getWorkflowNewFlag_in1 = "";
        ArrayOfString _getWorkflowNewFlag__return = port.getWorkflowNewFlag(_getWorkflowNewFlag_in0, _getWorkflowNewFlag_in1);
        System.out.println("getWorkflowNewFlag.result=" + _getWorkflowNewFlag__return);


        }
        {
        System.out.println("Invoking writeWorkflowReadFlag...");
        String _writeWorkflowReadFlag_in0 = "";
        String _writeWorkflowReadFlag_in1 = "";
        port.writeWorkflowReadFlag(_writeWorkflowReadFlag_in0, _writeWorkflowReadFlag_in1);


        }
        {
        System.out.println("Invoking getMyWorkflowRequestCount...");
        int _getMyWorkflowRequestCount_in0 = 0;
        ArrayOfString _getMyWorkflowRequestCount_in1 = null;
        int _getMyWorkflowRequestCount__return = port.getMyWorkflowRequestCount(_getMyWorkflowRequestCount_in0, _getMyWorkflowRequestCount_in1);
        System.out.println("getMyWorkflowRequestCount.result=" + _getMyWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getDoingWorkflowRequestList...");
        int _getDoingWorkflowRequestList_in0 = 0;
        int _getDoingWorkflowRequestList_in1 = 0;
        int _getDoingWorkflowRequestList_in2 = 0;
        int _getDoingWorkflowRequestList_in3 = 0;
        ArrayOfString _getDoingWorkflowRequestList_in4 = null;
        boolean _getDoingWorkflowRequestList_in5 = false;
        ArrayOfWorkflowRequestInfo _getDoingWorkflowRequestList__return = port.getDoingWorkflowRequestList(_getDoingWorkflowRequestList_in0, _getDoingWorkflowRequestList_in1, _getDoingWorkflowRequestList_in2, _getDoingWorkflowRequestList_in3, _getDoingWorkflowRequestList_in4, _getDoingWorkflowRequestList_in5);
        System.out.println("getDoingWorkflowRequestList.result=" + _getDoingWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking deleteRequest...");
        int _deleteRequest_in0 = 0;
        int _deleteRequest_in1 = 0;
        boolean _deleteRequest__return = port.deleteRequest(_deleteRequest_in0, _deleteRequest_in1);
        System.out.println("deleteRequest.result=" + _deleteRequest__return);


        }
        {
        System.out.println("Invoking getUserId...");
        String _getUserId_in0 = "";
        String _getUserId_in1 = "";
        String _getUserId__return = port.getUserId(_getUserId_in0, _getUserId_in1);
        System.out.println("getUserId.result=" + _getUserId__return);


        }
        {
        System.out.println("Invoking getCreateWorkflowTypeCount...");
        int _getCreateWorkflowTypeCount_in0 = 0;
        ArrayOfString _getCreateWorkflowTypeCount_in1 = null;
        int _getCreateWorkflowTypeCount__return = port.getCreateWorkflowTypeCount(_getCreateWorkflowTypeCount_in0, _getCreateWorkflowTypeCount_in1);
        System.out.println("getCreateWorkflowTypeCount.result=" + _getCreateWorkflowTypeCount__return);


        }
        {
        System.out.println("Invoking getWorkflowRequestLogs...");
        String _getWorkflowRequestLogs_in0 = "";
        String _getWorkflowRequestLogs_in1 = "";
        int _getWorkflowRequestLogs_in2 = 0;
        int _getWorkflowRequestLogs_in3 = 0;
        int _getWorkflowRequestLogs_in4 = 0;
        ArrayOfWorkflowRequestLog _getWorkflowRequestLogs__return = port.getWorkflowRequestLogs(_getWorkflowRequestLogs_in0, _getWorkflowRequestLogs_in1, _getWorkflowRequestLogs_in2, _getWorkflowRequestLogs_in3, _getWorkflowRequestLogs_in4);
        System.out.println("getWorkflowRequestLogs.result=" + _getWorkflowRequestLogs__return);


        }
        {
        System.out.println("Invoking getBeRejectWorkflowRequestList...");
        int _getBeRejectWorkflowRequestList_in0 = 0;
        int _getBeRejectWorkflowRequestList_in1 = 0;
        int _getBeRejectWorkflowRequestList_in2 = 0;
        int _getBeRejectWorkflowRequestList_in3 = 0;
        ArrayOfString _getBeRejectWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getBeRejectWorkflowRequestList__return = port.getBeRejectWorkflowRequestList(_getBeRejectWorkflowRequestList_in0, _getBeRejectWorkflowRequestList_in1, _getBeRejectWorkflowRequestList_in2, _getBeRejectWorkflowRequestList_in3, _getBeRejectWorkflowRequestList_in4);
        System.out.println("getBeRejectWorkflowRequestList.result=" + _getBeRejectWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking getCCWorkflowRequestCount...");
        int _getCCWorkflowRequestCount_in0 = 0;
        ArrayOfString _getCCWorkflowRequestCount_in1 = null;
        int _getCCWorkflowRequestCount__return = port.getCCWorkflowRequestCount(_getCCWorkflowRequestCount_in0, _getCCWorkflowRequestCount_in1);
        System.out.println("getCCWorkflowRequestCount.result=" + _getCCWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getToBeReadWorkflowRequestList...");
        int _getToBeReadWorkflowRequestList_in0 = 0;
        int _getToBeReadWorkflowRequestList_in1 = 0;
        int _getToBeReadWorkflowRequestList_in2 = 0;
        int _getToBeReadWorkflowRequestList_in3 = 0;
        ArrayOfString _getToBeReadWorkflowRequestList_in4 = null;
        boolean _getToBeReadWorkflowRequestList_in5 = false;
        ArrayOfWorkflowRequestInfo _getToBeReadWorkflowRequestList__return = port.getToBeReadWorkflowRequestList(_getToBeReadWorkflowRequestList_in0, _getToBeReadWorkflowRequestList_in1, _getToBeReadWorkflowRequestList_in2, _getToBeReadWorkflowRequestList_in3, _getToBeReadWorkflowRequestList_in4, _getToBeReadWorkflowRequestList_in5);
        System.out.println("getToBeReadWorkflowRequestList.result=" + _getToBeReadWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking getForwardWorkflowRequestList...");
        int _getForwardWorkflowRequestList_in0 = 0;
        int _getForwardWorkflowRequestList_in1 = 0;
        int _getForwardWorkflowRequestList_in2 = 0;
        int _getForwardWorkflowRequestList_in3 = 0;
        ArrayOfString _getForwardWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getForwardWorkflowRequestList__return = port.getForwardWorkflowRequestList(_getForwardWorkflowRequestList_in0, _getForwardWorkflowRequestList_in1, _getForwardWorkflowRequestList_in2, _getForwardWorkflowRequestList_in3, _getForwardWorkflowRequestList_in4);
        System.out.println("getForwardWorkflowRequestList.result=" + _getForwardWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking getMyWorkflowRequestList...");
        int _getMyWorkflowRequestList_in0 = 0;
        int _getMyWorkflowRequestList_in1 = 0;
        int _getMyWorkflowRequestList_in2 = 0;
        int _getMyWorkflowRequestList_in3 = 0;
        ArrayOfString _getMyWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getMyWorkflowRequestList__return = port.getMyWorkflowRequestList(_getMyWorkflowRequestList_in0, _getMyWorkflowRequestList_in1, _getMyWorkflowRequestList_in2, _getMyWorkflowRequestList_in3, _getMyWorkflowRequestList_in4);
        System.out.println("getMyWorkflowRequestList.result=" + _getMyWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking getDoingWorkflowRequestCount...");
        int _getDoingWorkflowRequestCount_in0 = 0;
        ArrayOfString _getDoingWorkflowRequestCount_in1 = null;
        boolean _getDoingWorkflowRequestCount_in2 = false;
        int _getDoingWorkflowRequestCount__return = port.getDoingWorkflowRequestCount(_getDoingWorkflowRequestCount_in0, _getDoingWorkflowRequestCount_in1, _getDoingWorkflowRequestCount_in2);
        System.out.println("getDoingWorkflowRequestCount.result=" + _getDoingWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getAllWorkflowRequestCount...");
        int _getAllWorkflowRequestCount_in0 = 0;
        ArrayOfString _getAllWorkflowRequestCount_in1 = null;
        int _getAllWorkflowRequestCount__return = port.getAllWorkflowRequestCount(_getAllWorkflowRequestCount_in0, _getAllWorkflowRequestCount_in1);
        System.out.println("getAllWorkflowRequestCount.result=" + _getAllWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getToDoWorkflowRequestList4OS...");
        int _getToDoWorkflowRequestList4OS_in0 = 0;
        int _getToDoWorkflowRequestList4OS_in1 = 0;
        int _getToDoWorkflowRequestList4OS_in2 = 0;
        int _getToDoWorkflowRequestList4OS_in3 = 0;
        ArrayOfString _getToDoWorkflowRequestList4OS_in4 = null;
        boolean _getToDoWorkflowRequestList4OS_in5 = false;
        ArrayOfWorkflowRequestInfo _getToDoWorkflowRequestList4OS__return = port.getToDoWorkflowRequestList4OS(_getToDoWorkflowRequestList4OS_in0, _getToDoWorkflowRequestList4OS_in1, _getToDoWorkflowRequestList4OS_in2, _getToDoWorkflowRequestList4OS_in3, _getToDoWorkflowRequestList4OS_in4, _getToDoWorkflowRequestList4OS_in5);
        System.out.println("getToDoWorkflowRequestList4OS.result=" + _getToDoWorkflowRequestList4OS__return);


        }
        {
        System.out.println("Invoking getHendledWorkflowRequestCount...");
        int _getHendledWorkflowRequestCount_in0 = 0;
        ArrayOfString _getHendledWorkflowRequestCount_in1 = null;
        int _getHendledWorkflowRequestCount__return = port.getHendledWorkflowRequestCount(_getHendledWorkflowRequestCount_in0, _getHendledWorkflowRequestCount_in1);
        System.out.println("getHendledWorkflowRequestCount.result=" + _getHendledWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking forwardWorkflowRequest...");
        int _forwardWorkflowRequest_in0 = 0;
        String _forwardWorkflowRequest_in1 = "";
        String _forwardWorkflowRequest_in2 = "";
        int _forwardWorkflowRequest_in3 = 0;
        String _forwardWorkflowRequest_in4 = "";
        String _forwardWorkflowRequest__return = port.forwardWorkflowRequest(_forwardWorkflowRequest_in0, _forwardWorkflowRequest_in1, _forwardWorkflowRequest_in2, _forwardWorkflowRequest_in3, _forwardWorkflowRequest_in4);
        System.out.println("forwardWorkflowRequest.result=" + _forwardWorkflowRequest__return);


        }
        {
        System.out.println("Invoking getCreateWorkflowCount...");
        int _getCreateWorkflowCount_in0 = 0;
        int _getCreateWorkflowCount_in1 = 0;
        ArrayOfString _getCreateWorkflowCount_in2 = null;
        int _getCreateWorkflowCount__return = port.getCreateWorkflowCount(_getCreateWorkflowCount_in0, _getCreateWorkflowCount_in1, _getCreateWorkflowCount_in2);
        System.out.println("getCreateWorkflowCount.result=" + _getCreateWorkflowCount__return);


        }
        {
        System.out.println("Invoking getToBeReadWorkflowRequestCount...");
        int _getToBeReadWorkflowRequestCount_in0 = 0;
        ArrayOfString _getToBeReadWorkflowRequestCount_in1 = null;
        boolean _getToBeReadWorkflowRequestCount_in2 = false;
        int _getToBeReadWorkflowRequestCount__return = port.getToBeReadWorkflowRequestCount(_getToBeReadWorkflowRequestCount_in0, _getToBeReadWorkflowRequestCount_in1, _getToBeReadWorkflowRequestCount_in2);
        System.out.println("getToBeReadWorkflowRequestCount.result=" + _getToBeReadWorkflowRequestCount__return);


        }
        {
        System.out.println("Invoking getAllWorkflowRequestList...");
        int _getAllWorkflowRequestList_in0 = 0;
        int _getAllWorkflowRequestList_in1 = 0;
        int _getAllWorkflowRequestList_in2 = 0;
        int _getAllWorkflowRequestList_in3 = 0;
        ArrayOfString _getAllWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getAllWorkflowRequestList__return = port.getAllWorkflowRequestList(_getAllWorkflowRequestList_in0, _getAllWorkflowRequestList_in1, _getAllWorkflowRequestList_in2, _getAllWorkflowRequestList_in3, _getAllWorkflowRequestList_in4);
        System.out.println("getAllWorkflowRequestList.result=" + _getAllWorkflowRequestList__return);


        }
        {
        System.out.println("Invoking forward2WorkflowRequest...");
        int _forward2WorkflowRequest_in0 = 0;
        String _forward2WorkflowRequest_in1 = "";
        String _forward2WorkflowRequest_in2 = "";
        int _forward2WorkflowRequest_in3 = 0;
        String _forward2WorkflowRequest_in4 = "";
        String _forward2WorkflowRequest__return = port.forward2WorkflowRequest(_forward2WorkflowRequest_in0, _forward2WorkflowRequest_in1, _forward2WorkflowRequest_in2, _forward2WorkflowRequest_in3, _forward2WorkflowRequest_in4);
        System.out.println("forward2WorkflowRequest.result=" + _forward2WorkflowRequest__return);


        }
        {
        System.out.println("Invoking getCCWorkflowRequestCount4OS...");
        int _getCCWorkflowRequestCount4OS_in0 = 0;
        ArrayOfString _getCCWorkflowRequestCount4OS_in1 = null;
        boolean _getCCWorkflowRequestCount4OS_in2 = false;
        int _getCCWorkflowRequestCount4OS__return = port.getCCWorkflowRequestCount4OS(_getCCWorkflowRequestCount4OS_in0, _getCCWorkflowRequestCount4OS_in1, _getCCWorkflowRequestCount4OS_in2);
        System.out.println("getCCWorkflowRequestCount4OS.result=" + _getCCWorkflowRequestCount4OS__return);


        }
        {
        System.out.println("Invoking getToDoWorkflowRequestList...");
        int _getToDoWorkflowRequestList_in0 = 0;
        int _getToDoWorkflowRequestList_in1 = 0;
        int _getToDoWorkflowRequestList_in2 = 0;
        int _getToDoWorkflowRequestList_in3 = 0;
        ArrayOfString _getToDoWorkflowRequestList_in4 = null;
        ArrayOfWorkflowRequestInfo _getToDoWorkflowRequestList__return = port.getToDoWorkflowRequestList(_getToDoWorkflowRequestList_in0, _getToDoWorkflowRequestList_in1, _getToDoWorkflowRequestList_in2, _getToDoWorkflowRequestList_in3, _getToDoWorkflowRequestList_in4);
        System.out.println("getToDoWorkflowRequestList.result=" + _getToDoWorkflowRequestList__return);


        }

        System.exit(0);
    }

}
