package com.bluetop.engin.api.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-03-31T21:44:18.610+08:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "webservices.services.weaver.com.cn", name = "WorkflowServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WorkflowServicePortType {

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount4Ofs")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount4Ofs", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestCount4Ofs")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCount4OfsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestCount4OfsResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getHendledWorkflowRequestCount4Ofs(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList4OS")
    @RequestWrapper(localName = "getMyWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getMyWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestList4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getMyWorkflowRequestList4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeList")
    @RequestWrapper(localName = "getCreateWorkflowTypeList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowTypeList")
    @ResponseWrapper(localName = "getCreateWorkflowTypeListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowTypeListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowTypeList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getBeRejectWorkflowRequestCount")
    @RequestWrapper(localName = "getBeRejectWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetBeRejectWorkflowRequestCount")
    @ResponseWrapper(localName = "getBeRejectWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetBeRejectWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getBeRejectWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount4OS")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestCount4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getProcessedWorkflowRequestCount4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList")
    @RequestWrapper(localName = "getCCWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestList")
    @ResponseWrapper(localName = "getCCWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getCCWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.givingOpinions")
    @RequestWrapper(localName = "givingOpinions", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GivingOpinions")
    @ResponseWrapper(localName = "givingOpinionsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GivingOpinionsResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String givingOpinions(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    String in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestCount")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getToDoWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getForwardWorkflowRequestCount")
    @RequestWrapper(localName = "getForwardWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetForwardWorkflowRequestCount")
    @ResponseWrapper(localName = "getForwardWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetForwardWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getForwardWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList4OS")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestList4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getProcessedWorkflowRequestList4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestList")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getProcessedWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doForceOver")
    @RequestWrapper(localName = "doForceOver", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoForceOver")
    @ResponseWrapper(localName = "doForceOverResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoForceOverResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String doForceOver(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount4OS")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestCount4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getToDoWorkflowRequestCount4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doCreateWorkflowRequest")
    @RequestWrapper(localName = "doCreateWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoCreateWorkflowRequest")
    @ResponseWrapper(localName = "doCreateWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoCreateWorkflowRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String doCreateWorkflowRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    WorkflowRequestInfo in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowRequestInfo")
    @RequestWrapper(localName = "getCreateWorkflowRequestInfo", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowRequestInfo")
    @ResponseWrapper(localName = "getCreateWorkflowRequestInfoResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowRequestInfoResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public WorkflowRequestInfo getCreateWorkflowRequestInfo(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList4Ofs")
    @RequestWrapper(localName = "getHendledWorkflowRequestList4Ofs", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestList4Ofs")
    @ResponseWrapper(localName = "getHendledWorkflowRequestList4OfsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestList4OfsResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getHendledWorkflowRequestList4Ofs(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList4OS")
    @RequestWrapper(localName = "getCCWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getCCWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestList4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getCCWorkflowRequestList4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getLeaveDays")
    @RequestWrapper(localName = "getLeaveDays", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetLeaveDays")
    @ResponseWrapper(localName = "getLeaveDaysResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetLeaveDaysResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String getLeaveDays(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    String in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount4OS")
    @RequestWrapper(localName = "getMyWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getMyWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestCount4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getMyWorkflowRequestCount4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doCreateRequest")
    @RequestWrapper(localName = "doCreateRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoCreateRequest")
    @ResponseWrapper(localName = "doCreateRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DoCreateRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String doCreateRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    WorkflowRequestInfo in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestCount")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetProcessedWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getProcessedWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowList")
    @RequestWrapper(localName = "getCreateWorkflowList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowList")
    @ResponseWrapper(localName = "getCreateWorkflowListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    int in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest")
    @RequestWrapper(localName = "getWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequest")
    @ResponseWrapper(localName = "getWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public WorkflowRequestInfo getWorkflowRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2
    );

    @WebMethod(operationName = "getWorkflowRequest4split", action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest4split")
    @RequestWrapper(localName = "getWorkflowRequest4split", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequest4Split")
    @ResponseWrapper(localName = "getWorkflowRequest4splitResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequest4SplitResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public WorkflowRequestInfo getWorkflowRequest4Split(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.submitWorkflowRequest")
    @RequestWrapper(localName = "submitWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.SubmitWorkflowRequest")
    @ResponseWrapper(localName = "submitWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.SubmitWorkflowRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String submitWorkflowRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    WorkflowRequestInfo in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    String in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    String in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList")
    @RequestWrapper(localName = "getHendledWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestList")
    @ResponseWrapper(localName = "getHendledWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getHendledWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowNewFlag")
    @RequestWrapper(localName = "getWorkflowNewFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowNewFlag")
    @ResponseWrapper(localName = "getWorkflowNewFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowNewFlagResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfString getWorkflowNewFlag(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.writeWorkflowReadFlag")
    @RequestWrapper(localName = "writeWorkflowReadFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.WriteWorkflowReadFlag")
    @ResponseWrapper(localName = "writeWorkflowReadFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.WriteWorkflowReadFlagResponse")
    public void writeWorkflowReadFlag(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount")
    @RequestWrapper(localName = "getMyWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestCount")
    @ResponseWrapper(localName = "getMyWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getMyWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getDoingWorkflowRequestList")
    @RequestWrapper(localName = "getDoingWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetDoingWorkflowRequestList")
    @ResponseWrapper(localName = "getDoingWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetDoingWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getDoingWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.deleteRequest")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.DeleteRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public boolean deleteRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getUserid")
    @RequestWrapper(localName = "getUserId", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetUserIdResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String getUserId(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeCount")
    @RequestWrapper(localName = "getCreateWorkflowTypeCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowTypeCount")
    @ResponseWrapper(localName = "getCreateWorkflowTypeCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowTypeCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getCreateWorkflowTypeCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequestLogs")
    @RequestWrapper(localName = "getWorkflowRequestLogs", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequestLogs")
    @ResponseWrapper(localName = "getWorkflowRequestLogsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetWorkflowRequestLogsResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestLog getWorkflowRequestLogs(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    String in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    int in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getBeRejectWorkflowRequestList")
    @RequestWrapper(localName = "getBeRejectWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetBeRejectWorkflowRequestList")
    @ResponseWrapper(localName = "getBeRejectWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetBeRejectWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getBeRejectWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount")
    @RequestWrapper(localName = "getCCWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestCount")
    @ResponseWrapper(localName = "getCCWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getCCWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToBeReadWorkflowRequestList")
    @RequestWrapper(localName = "getToBeReadWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToBeReadWorkflowRequestList")
    @ResponseWrapper(localName = "getToBeReadWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToBeReadWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getToBeReadWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getForwardWorkflowRequestList")
    @RequestWrapper(localName = "getForwardWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetForwardWorkflowRequestList")
    @ResponseWrapper(localName = "getForwardWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetForwardWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getForwardWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList")
    @RequestWrapper(localName = "getMyWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestList")
    @ResponseWrapper(localName = "getMyWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetMyWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getMyWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getDoingWorkflowRequestCount")
    @RequestWrapper(localName = "getDoingWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetDoingWorkflowRequestCount")
    @ResponseWrapper(localName = "getDoingWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetDoingWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getDoingWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestCount")
    @RequestWrapper(localName = "getAllWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetAllWorkflowRequestCount")
    @ResponseWrapper(localName = "getAllWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetAllWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getAllWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList4OS")
    @RequestWrapper(localName = "getToDoWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getToDoWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestList4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getToDoWorkflowRequestList4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4,
            @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in5
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestCount")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetHendledWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getHendledWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forwardWorkflowRequest")
    @RequestWrapper(localName = "forwardWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.ForwardWorkflowRequest")
    @ResponseWrapper(localName = "forwardWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.ForwardWorkflowRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String forwardWorkflowRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    String in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowCount")
    @RequestWrapper(localName = "getCreateWorkflowCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowCount")
    @ResponseWrapper(localName = "getCreateWorkflowCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCreateWorkflowCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getCreateWorkflowCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToBeReadWorkflowRequestCount")
    @RequestWrapper(localName = "getToBeReadWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToBeReadWorkflowRequestCount")
    @ResponseWrapper(localName = "getToBeReadWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToBeReadWorkflowRequestCountResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getToBeReadWorkflowRequestCount(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestList")
    @RequestWrapper(localName = "getAllWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetAllWorkflowRequestList")
    @ResponseWrapper(localName = "getAllWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetAllWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getAllWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forward2WorkflowRequest")
    @RequestWrapper(localName = "forward2WorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.Forward2WorkflowRequest")
    @ResponseWrapper(localName = "forward2WorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.Forward2WorkflowRequestResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public String forward2WorkflowRequest(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    String in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    String in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    String in4
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount4OS")
    @RequestWrapper(localName = "getCCWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getCCWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetCCWorkflowRequestCount4OSResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public int getCCWorkflowRequestCount4OS(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    boolean in2
    );

    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList")
    @RequestWrapper(localName = "getToDoWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestList")
    @ResponseWrapper(localName = "getToDoWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "com.bluetop.engin.api.webservice.GetToDoWorkflowRequestListResponse")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    public ArrayOfWorkflowRequestInfo getToDoWorkflowRequestList(

            @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
                    int in0,
            @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
                    int in1,
            @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
                    int in2,
            @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
                    int in3,
            @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
                    ArrayOfString in4
    );
}
