server:
  port: 7001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.205/wl_core_hk?useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: dev
    password: dev
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1200000